name: build-docs

on:
  push:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Python version
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12 

      # Install Poetry
      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Add Poetry to PATH
        run: echo "/home/runner/.local/bin" >> $GITHUB_PATH

      # Install dependencies
      - name: Install dependencies
        run: poetry install --with dev

      # Genereate docs
      - name: Build HTML documentation
        run: poetry run make html

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  
          publish_dir: docs/build/html  
          publish_branch: gh-pages
          clean: true